[workspace]
members = [
    "server",
    "web",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.204", features = ["derive"] }
anyhow = "1.0.86"
serde_json = "1.0.124"
resolver = "2"
chrono = { version = "0.4.38", features = ["serde"] }
